# Generated by Django 3.2.4 on 2021-07-02 15:11
import uuid

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('shorturl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID,
                                        editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict, null=True)),
                ('short_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                related_name='hits', to='shorturl.shorturl')),
            ],
        ),
    ]
